spring.datasource.web.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.web.jdbc-url=jdbc:mariadb://183.110.62.52:13306/MaumMcc
spring.datasource.web.username=maummcc
spring.datasource.web.password=maum!2024!

Globals.fileStorePath=/data/ibk-upload
Globals.fileStoreUriPath=/upload
Globals.domain.full=https://admsys.ibk.net
