server.port=18082

#DEV false / REAL true
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.prefix=/templates
spring.thymeleaf.suffix=.html

spring.output.ansi.enabled=always

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

logging.level.org.springframework.context=DEBUG
logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type=trace
#logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.datasource.hikari.maximum-pool-size=4

spring.datasource.web.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.web.jdbc-url=jdbc:mariadb://ibk_mcc_db:3306/maummcc
spring.datasource.web.username=maummcc
spring.datasource.web.password=maum!2024!

# fileupload maxsize setting
spring.servlet.multipart.maxFileSize=10MB
spring.servlet.multipart.maxRequestSize=10MB

#mail host/port/hostname
Globals.mail.host=172.18.37.22
Globals.mail.port=25
Globals.mail.hostname=gwmail.ibk.co.kr
#messaenger settings
Globals.messenger.domain=http://172.18.123.43:8010
Globals.messenger.srvCode=BBSBBS
#MCC url
Globals.domain.mcc=http://10.50.3.21:9001
#web url
Globals.domain.web=http://10.50.3.18:18081
#MCC check flag
Globals.check.mcc=true
#web check flag
Globals.check.web=true
#mail send flag
Globals.check.mail=true
#messenger send flag
Globals.check.messenger=true