server.port=18082

#DEV false / REAL true
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.prefix=/templates
spring.thymeleaf.suffix=.html

spring.output.ansi.enabled=always

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

#logging.path: D:/logs
logging.level.kr.co.ibk_monitoring=DEBUG
logging.level.org.springframework.context=DEBUG
logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type=trace
#logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.com.zaxxer.hikari=DEBUG

spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.max-lifetime=1800000

spring.datasource.web.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.web.jdbc-url=jdbc:mariadb://ibk_mcc_db:3306/maummcc
spring.datasource.web.username=maummcc
spring.datasource.web.password=maum!2024!

# fileupload maxsize setting
spring.servlet.multipart.maxFileSize=10MB
spring.servlet.multipart.maxRequestSize=10MB

#mail host/port/hostname
Globals.mail.host=172.18.121.168
Globals.mail.port=25
Globals.mail.hostname=gwmail.ibk.co.kr
#messaenger settings
Globals.messenger.domain=http://172.18.123.43:8010
Globals.messenger.srvCode=BBSBBS
#MCC url
Globals.domain.mcc1=http://172.18.10.47:9001
Globals.domain.mcc2=http://172.18.10.47:9002
#web url
Globals.domain.web=http://172.18.121.157:18081
#MCC check flag
Globals.check.mcc1=false
Globals.check.mcc2=false
#web check flag
Globals.check.web=true
#mail send flag
Globals.check.mail=false
#messenger send flag
Globals.check.messenger=false

# data match flag
Globals.check.dataMatch=true
# data match cron setting (min(0-59), hour(0-23), day(1-31), mon(1-12), week(0: SUN, 1: MON, 2:TUE, 3:WED, 4:TUR, 5:FRI, 6:SAT))
Globals.batch.dataMatch.cron.min=0
Globals.batch.dataMatch.cron.hour=5
Globals.batch.dataMatch.cron.day=*
Globals.batch.dataMatch.cron.mon=*
Globals.batch.dataMatch.cron.week=*