
#DEV false / REAL true
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.prefix=/templates
spring.thymeleaf.suffix=.html

spring.output.ansi.enabled=always

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

#logging.path: D:/logs
logging.level.org.springframework.context=DEBUG
logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type=trace
#logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.com.zaxxer.hikari=DEBUG

spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.max-lifetime=1800000

#n2 dev
spring.datasource.web.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.web.jdbc-url=jdbc:mariadb://ibk_msg_db_master:3306/maummcc
spring.datasource.web.username=maummcc
spring.datasource.web.password=maum!2024!

Globals.fileStorePath=/ibk_file
Globals.fileStoreUriPath=/upload
Globals.batchInfer.card.fileName=batch_infer
Globals.batchInfer.bill.fileName=tax_batch_infer
Globals.batchInfer.ext=.sh
Globals.batchInfer.backupFileStorePath=/ibk_file/batch_infer_backup
Globals.domain.full=http://10.50.3.18:18081
Globals.domain.card.mcc=http://10.50.3.21:9001
Globals.domain.bill.mcc=http://10.50.3.21:9002
Globals.status.domain=http://10.50.3.18:18082

# fileupload maxsize setting
spring.servlet.multipart.maxFileSize=10MB
spring.servlet.multipart.maxRequestSize=10MB

#scheduler flag
Globals.check.scheduler=false

#statistic batch flag
Globals.check.statistic=false

#statistic by range batch flag
Globals.check.statistic.range=false

#hit batch cron setting (min(0-59), hour(0-23), day(1-31), mon(1-12), week(0: SUN, 1: MON, 2:TUE, 3:WED, 4:TUR, 5:FRI, 6:SAT))
# ?? ??? hit ???? ?? 1?? ?? ????? ?
Globals.batch.statistic.cron.min=30
Globals.batch.statistic.cron.hour=3
Globals.batch.statistic.cron.day=*
Globals.batch.statistic.cron.mon=*
Globals.batch.statistic.cron.week=1

#hit batch flag
Globals.check.hit=false

#hit batch cron setting (min(0-59), hour(0-23), day(1-31), mon(1-12), week(0: SUN, 1: MON, 2:TUE, 3:WED, 4:TUR, 5:FRI, 6:SAT))
Globals.batch.hit.cron.min=30
Globals.batch.hit.cron.hour=4
Globals.batch.hit.cron.day=*
Globals.batch.hit.cron.mon=*
Globals.batch.hit.cron.week=1

#excel data partition
excel.data.partition.count=20000