# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import ibk_mcc_engine_control_pb2 as proto_dot_ibk__mcc__engine__control__pb2
from . import mcc_pb2 as proto_dot_mcc__pb2


class MccEngineControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckEngineStatus = channel.unary_unary(
                '/maum.brain.mcc.MccEngineController/CheckEngineStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_ibk__mcc__engine__control__pb2.ControlResponse.FromString,
                )
        self.StartTraining = channel.unary_unary(
                '/maum.brain.mcc.MccEngineController/StartTraining',
                request_serializer=proto_dot_ibk__mcc__engine__control__pb2.TrainingParams.SerializeToString,
                response_deserializer=proto_dot_ibk__mcc__engine__control__pb2.ControlResponse.FromString,
                )
        self.CheckModelStatus = channel.unary_unary(
                '/maum.brain.mcc.MccEngineController/CheckModelStatus',
                request_serializer=proto_dot_ibk__mcc__engine__control__pb2.ModelInformation.SerializeToString,
                response_deserializer=proto_dot_ibk__mcc__engine__control__pb2.ModelStatus.FromString,
                )
        self.StopTraining = channel.unary_unary(
                '/maum.brain.mcc.MccEngineController/StopTraining',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_ibk__mcc__engine__control__pb2.ControlResponse.FromString,
                )
        self.ReplaceModel = channel.unary_unary(
                '/maum.brain.mcc.MccEngineController/ReplaceModel',
                request_serializer=proto_dot_ibk__mcc__engine__control__pb2.ReplaceModelRequest.SerializeToString,
                response_deserializer=proto_dot_ibk__mcc__engine__control__pb2.ControlResponse.FromString,
                )
        self.WrappedInference = channel.unary_unary(
                '/maum.brain.mcc.MccEngineController/WrappedInference',
                request_serializer=proto_dot_mcc__pb2.TextClassificationRequest.SerializeToString,
                response_deserializer=proto_dot_ibk__mcc__engine__control__pb2.InferenceResponse.FromString,
                )


class MccEngineControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckEngineStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckModelStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaceModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WrappedInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MccEngineControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckEngineStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckEngineStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_ibk__mcc__engine__control__pb2.ControlResponse.SerializeToString,
            ),
            'StartTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTraining,
                    request_deserializer=proto_dot_ibk__mcc__engine__control__pb2.TrainingParams.FromString,
                    response_serializer=proto_dot_ibk__mcc__engine__control__pb2.ControlResponse.SerializeToString,
            ),
            'CheckModelStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckModelStatus,
                    request_deserializer=proto_dot_ibk__mcc__engine__control__pb2.ModelInformation.FromString,
                    response_serializer=proto_dot_ibk__mcc__engine__control__pb2.ModelStatus.SerializeToString,
            ),
            'StopTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTraining,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_ibk__mcc__engine__control__pb2.ControlResponse.SerializeToString,
            ),
            'ReplaceModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaceModel,
                    request_deserializer=proto_dot_ibk__mcc__engine__control__pb2.ReplaceModelRequest.FromString,
                    response_serializer=proto_dot_ibk__mcc__engine__control__pb2.ControlResponse.SerializeToString,
            ),
            'WrappedInference': grpc.unary_unary_rpc_method_handler(
                    servicer.WrappedInference,
                    request_deserializer=proto_dot_mcc__pb2.TextClassificationRequest.FromString,
                    response_serializer=proto_dot_ibk__mcc__engine__control__pb2.InferenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'maum.brain.mcc.MccEngineController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MccEngineController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckEngineStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/maum.brain.mcc.MccEngineController/CheckEngineStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_ibk__mcc__engine__control__pb2.ControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/maum.brain.mcc.MccEngineController/StartTraining',
            proto_dot_ibk__mcc__engine__control__pb2.TrainingParams.SerializeToString,
            proto_dot_ibk__mcc__engine__control__pb2.ControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckModelStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/maum.brain.mcc.MccEngineController/CheckModelStatus',
            proto_dot_ibk__mcc__engine__control__pb2.ModelInformation.SerializeToString,
            proto_dot_ibk__mcc__engine__control__pb2.ModelStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/maum.brain.mcc.MccEngineController/StopTraining',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_ibk__mcc__engine__control__pb2.ControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplaceModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/maum.brain.mcc.MccEngineController/ReplaceModel',
            proto_dot_ibk__mcc__engine__control__pb2.ReplaceModelRequest.SerializeToString,
            proto_dot_ibk__mcc__engine__control__pb2.ControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WrappedInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/maum.brain.mcc.MccEngineController/WrappedInference',
            proto_dot_mcc__pb2.TextClassificationRequest.SerializeToString,
            proto_dot_ibk__mcc__engine__control__pb2.InferenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
