# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/mcc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/mcc.proto',
  package='maum.brain.mcc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fproto/mcc.proto\x12\x0emaum.brain.mcc\"H\n\x19TextClassificationRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12\x0e\n\x06\x66loats\x18\x03 \x03(\x02\"i\n\x1aMultiCategoryLabelResponse\x12K\n\x1a\x63\x61tegory_label_predictions\x18\x01 \x03(\x0b\x32\'.maum.brain.mcc.CategoryLabelPrediction\"g\n\x17\x43\x61tegoryLabelPrediction\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12:\n\x11label_predictions\x18\x02 \x03(\x0b\x32\x1f.maum.brain.mcc.LabelPrediction\"5\n\x0fLabelPrediction\x12\r\n\x05label\x18\x01 \x01(\t\x12\x13\n\x0bprobability\x18\x02 \x01(\x02\x32\x92\x01\n\x1bMultiCategoryTextClassifier\x12s\n\x1aGetMultiCategoryClassLabel\x12).maum.brain.mcc.TextClassificationRequest\x1a*.maum.brain.mcc.MultiCategoryLabelResponseb\x06proto3'
)




_TEXTCLASSIFICATIONREQUEST = _descriptor.Descriptor(
  name='TextClassificationRequest',
  full_name='maum.brain.mcc.TextClassificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='maum.brain.mcc.TextClassificationRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='top_k', full_name='maum.brain.mcc.TextClassificationRequest.top_k', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='floats', full_name='maum.brain.mcc.TextClassificationRequest.floats', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=107,
)


_MULTICATEGORYLABELRESPONSE = _descriptor.Descriptor(
  name='MultiCategoryLabelResponse',
  full_name='maum.brain.mcc.MultiCategoryLabelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='category_label_predictions', full_name='maum.brain.mcc.MultiCategoryLabelResponse.category_label_predictions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=214,
)


_CATEGORYLABELPREDICTION = _descriptor.Descriptor(
  name='CategoryLabelPrediction',
  full_name='maum.brain.mcc.CategoryLabelPrediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='maum.brain.mcc.CategoryLabelPrediction.category', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label_predictions', full_name='maum.brain.mcc.CategoryLabelPrediction.label_predictions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=319,
)


_LABELPREDICTION = _descriptor.Descriptor(
  name='LabelPrediction',
  full_name='maum.brain.mcc.LabelPrediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='maum.brain.mcc.LabelPrediction.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='probability', full_name='maum.brain.mcc.LabelPrediction.probability', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=374,
)

_MULTICATEGORYLABELRESPONSE.fields_by_name['category_label_predictions'].message_type = _CATEGORYLABELPREDICTION
_CATEGORYLABELPREDICTION.fields_by_name['label_predictions'].message_type = _LABELPREDICTION
DESCRIPTOR.message_types_by_name['TextClassificationRequest'] = _TEXTCLASSIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['MultiCategoryLabelResponse'] = _MULTICATEGORYLABELRESPONSE
DESCRIPTOR.message_types_by_name['CategoryLabelPrediction'] = _CATEGORYLABELPREDICTION
DESCRIPTOR.message_types_by_name['LabelPrediction'] = _LABELPREDICTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextClassificationRequest = _reflection.GeneratedProtocolMessageType('TextClassificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEXTCLASSIFICATIONREQUEST,
  '__module__' : 'proto.mcc_pb2'
  # @@protoc_insertion_point(class_scope:maum.brain.mcc.TextClassificationRequest)
  })
_sym_db.RegisterMessage(TextClassificationRequest)

MultiCategoryLabelResponse = _reflection.GeneratedProtocolMessageType('MultiCategoryLabelResponse', (_message.Message,), {
  'DESCRIPTOR' : _MULTICATEGORYLABELRESPONSE,
  '__module__' : 'proto.mcc_pb2'
  # @@protoc_insertion_point(class_scope:maum.brain.mcc.MultiCategoryLabelResponse)
  })
_sym_db.RegisterMessage(MultiCategoryLabelResponse)

CategoryLabelPrediction = _reflection.GeneratedProtocolMessageType('CategoryLabelPrediction', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYLABELPREDICTION,
  '__module__' : 'proto.mcc_pb2'
  # @@protoc_insertion_point(class_scope:maum.brain.mcc.CategoryLabelPrediction)
  })
_sym_db.RegisterMessage(CategoryLabelPrediction)

LabelPrediction = _reflection.GeneratedProtocolMessageType('LabelPrediction', (_message.Message,), {
  'DESCRIPTOR' : _LABELPREDICTION,
  '__module__' : 'proto.mcc_pb2'
  # @@protoc_insertion_point(class_scope:maum.brain.mcc.LabelPrediction)
  })
_sym_db.RegisterMessage(LabelPrediction)



_MULTICATEGORYTEXTCLASSIFIER = _descriptor.ServiceDescriptor(
  name='MultiCategoryTextClassifier',
  full_name='maum.brain.mcc.MultiCategoryTextClassifier',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=377,
  serialized_end=523,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMultiCategoryClassLabel',
    full_name='maum.brain.mcc.MultiCategoryTextClassifier.GetMultiCategoryClassLabel',
    index=0,
    containing_service=None,
    input_type=_TEXTCLASSIFICATIONREQUEST,
    output_type=_MULTICATEGORYLABELRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MULTICATEGORYTEXTCLASSIFIER)

DESCRIPTOR.services_by_name['MultiCategoryTextClassifier'] = _MULTICATEGORYTEXTCLASSIFIER

# @@protoc_insertion_point(module_scope)
