# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import mcc_pb2 as proto_dot_mcc__pb2


class MultiCategoryTextClassifierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMultiCategoryClassLabel = channel.unary_unary(
                '/maum.brain.mcc.MultiCategoryTextClassifier/GetMultiCategoryClassLabel',
                request_serializer=proto_dot_mcc__pb2.TextClassificationRequest.SerializeToString,
                response_deserializer=proto_dot_mcc__pb2.MultiCategoryLabelResponse.FromString,
                )


class MultiCategoryTextClassifierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMultiCategoryClassLabel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MultiCategoryTextClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMultiCategoryClassLabel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMultiCategoryClassLabel,
                    request_deserializer=proto_dot_mcc__pb2.TextClassificationRequest.FromString,
                    response_serializer=proto_dot_mcc__pb2.MultiCategoryLabelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'maum.brain.mcc.MultiCategoryTextClassifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MultiCategoryTextClassifier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMultiCategoryClassLabel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/maum.brain.mcc.MultiCategoryTextClassifier/GetMultiCategoryClassLabel',
            proto_dot_mcc__pb2.TextClassificationRequest.SerializeToString,
            proto_dot_mcc__pb2.MultiCategoryLabelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
