model_name: 0902_model2

# Configure below when you train a model
train:
    pretrained_ckpt: /pretrained/bert_kor_mecab/bert_model.ckpt
    vocab_file: /pretrained/bert_kor_mecab/vocab.txt

    data: /DATA/seonwoong/ibk/mcc_data/세금계산서/9월/0902_train.txt

    epochs: 1
    learning_rate: 3e-5
    warmup: 0.1
    batch_size: 8
    eval_batch_size: 8

    save_checkpoints_steps: 1e4
    save_summary_steps: 1e2
    log_step_count_steps: 1e2
    iterations_per_loop: 1e3


# Inference with a trained model
infer:
    batch_size: 1
    num_top_label: 3
    data: /DATA/seonwoong/ibk/mcc_data/세금계산서/9월/0902_test.txt     # for the test(batch inference)

num_process: 1     # > 1: CPU multi process  #TODO
seed_bucket: 100
