### dev ###

spring:
  config:
    activate:
      on-profile: dev
  maria:
    datasource:
      # MYSQL
      #driverClassName: com.mysql.cj.jdbc.Driver
      #url: jdbc:mysql://172.30.1.28:3306/sample_db?characterEncoding=UTF-8&serverTimezone=UTC

      # MARIADB
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://183.110.62.52:13306/maumxdc?characterEncoding=UTF-8&passwordCharacterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
      #jdbc-url: jdbc:mariadb://172.18.121.25:23306/maumxdc?characterEncoding=UTF-8&passwordCharacterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
      #jdbc-url: jdbc:mariadb://121.166.163.253:23306/maumxdc?characterEncoding=UTF-8&passwordCharacterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
      type: com.zaxxer.hikari.HikariDataSource
      username: maumxdc
      password: Lab!2022!

# log생성

# ----------------------------------------
# Logging
# ----------------------------------------
#logging:
#  level:
#    root: WARN
#  config: classpath:logback-${spring.config.activate.on-profile}-spring.xml
#  file:
#    path: ./logs/
#    name: mindslab

mindslab:
  config:
    testvalue: dev
    bprServerIp: 172.18.121.145
    bprServerPort: 18931
    bprImagePath: /bprImage
    learnExcelPath: /learn
    mindsLabApiUrl: http://172.18.121.25:9620
    #mindsLabApiUrl: http://183.110.62.52:9620
